export { default as Baby } from "./baby.svg"
export { default as Car } from "./car.svg"
export { default as House } from "./house.svg"
export { default as School } from "./school.svg"
export { default as Suitcase } from "./suitcase.svg"
export { default as Wallet } from "./wallet.svg"
